title: yuonch blog
description: > # this means to ignore newlines until "baseurl:"
  随便记录些东西
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: yuonch # add your name
author-img: head.jpeg # add your photo
about-author: 随便写写 # add description
github: yuonch # add your Github handle
linkedin: # add your Linkedin handle
email: yuonch@qq.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
